# Data configs
domainA_dir: 'D:\쓸거\test\20'
domainB_dir: 'D:\쓸거\test\60'

# Network Configs
ngf: 32
ndf: 32
n_blocks: 9

# Loss configs:
adv_weight: 2
cycle_weight: 10
identity_weight: 7

# Optimizer configs:
lr: 0.0001
weight_decay: 0.0001

# Training configs:
img_size: 128
batch_size: 1
num_workers: 4
epochs: 1
gpus: 1
